// <auto-generated />
namespace CodeFirstORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmappingdetailproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmappingdetailproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201905300646584_add-mapping detail-product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
